// Application constants

// SUNAT Document Types
export const SUNAT_DOC_TYPES = {
  '0': 'DOC.TRIB.NO.DOM.SIN.RUC',
  '1': 'DNI',
  '4': 'CARNET DE EXTRANJERIA',
  '6': 'RUC',
  '7': 'PASAPORTE',
  '11': 'PTP',
  '12': 'CEDULA DIPLOMATICA',
} as const

// SUNAT Document Types for Sales
export const SALES_DOC_TYPES = {
  '01': 'FACTURA',
  '03': 'BOLETA DE VENTA',
  '07': 'NOTA DE CREDITO',
  '08': 'NOTA DE DEBITO',
  '09': 'GUIA DE REMISION REMITENTE',
  '12': 'TICKET DE MAQUINA REGISTRADORA',
  '13': 'DOCUMENTO EMITIDO POR BANCOS',
} as const

// SUNAT Document Types for Purchases
export const PURCHASE_DOC_TYPES = {
  '01': 'FACTURA',
  '02': 'RECIBO POR HONORARIOS',
  '03': 'BOLETA DE VENTA',
  '04': 'LIQUIDACION DE COMPRA',
  '05': 'BOLETO DE TRANSPORTE AEREO',
  '06': 'CARTA DE PORTE AEREO',
  '07': 'NOTA DE CREDITO',
  '08': 'NOTA DE DEBITO',
  '09': 'GUIA DE REMISION REMITENTE',
  '10': 'RECIBO DE ARRENDAMIENTO',
  '11': 'POLIZA EMITIDA POR LAS BOLSAS DE VALORES',
  '12': 'TICKET DE MAQUINA REGISTRADORA',
  '13': 'DOCUMENTO EMITIDO POR BANCOS',
  '14': 'RECIBO SERVICIOS PUBLICOS',
  '15': 'BOLETO EMITIDO POR EL SERVICIO DE TRANSPORTE TERRESTRE',
  '16': 'BOLETO DE VIAJE EMITIDO POR LAS EMPRESAS DE TRANSPORTE PUBLICO',
  '18': 'DOCUMENTO EMITIDO POR LAS AFP',
  '19': 'BOLETO PARA ESPECTACULOS PUBLICOS',
  '20': 'COMPROBANTE DE RETENCION',
  '21': 'CONOCIMIENTO DE EMBARQUE POR EL SERVICIO DE TRANSPORTE DE CARGA MARITIMA',
  '22': 'COMPROBANTE POR OPERACIONES NO HABITUALES',
  '23': 'POLIZA DE ADJUDICACION O REMATE DE BIENES',
  '24': 'CERTIFICADO DE PAGO DE REGALIAS',
  '25': 'DOCUMENTO DE ATRIBUCION (GAS NATURAL)',
  '26': 'RECIBO POR EL PAGO DE LA TARIFA POR USO DE AGUA SUPERFICIAL',
  '27': 'SEGURO COMPLEMENTARIO DE TRABAJO DE RIESGO',
  '28': 'TARIFA UNIFICADA DE USO DE AEROPUERTO',
  '29': 'DOCUMENTO EMITIDO POR LA IGLESIA CATOLICA',
  '30': 'DOCUMENTO EMITIDO POR LAS ADMINISTRADORAS DE PEAJES',
  '31': 'DOCUMENTO EMITIDO POR LAS EMPRESAS QUE DESEMPEÑAN EL ROL ADQUIRENTE EN LOS SISTEMAS DE PAGO MEDIANTE TARJETAS DE CREDITO Y DEBITO',
  '32': 'DOCUMENTO EMITIDO POR LAS EMPRESAS RECAUDADORAS DE LA DENOMINADA GARANTIA DE RED PRINCIPAL A QUE SE REFIERE EL NUMERAL 7.6 DEL ARTICULO 7° DE LA LEY N° 27133 – LEY DE PROMOCION DEL DESARROLLO DE LA INDUSTRIA DEL GAS NATURAL',
  '34': 'DOCUMENTO DEL OPERADOR',
  '35': 'DOCUMENTO DEL PARTICIPE',
  '36': 'RECIBO DE DISTRIBUCION DE GAS NATURAL',
  '37': 'DOCUMENTO PREVIO',
  '40': 'CONSTANCIA DE DEPOSITO - DETRACCION',
  '41': 'COMPROBANTE DE PERCEPCION',
  '43': 'BOLETO EMITIDO POR LAS EMPRESAS DE TRANSPORTE PUBLICO INTERPROVINCIAL DE PASAJEROS DENTRO DEL PAIS',
  '44': 'BOLETO EMITIDO POR LAS EMPRESAS DE TRANSPORTE NACIONAL DE PASAJEROS MARITIMO Y FLUVIAL',
  '45': 'BOLETO EMITIDO POR LAS EMPRESAS DE TRANSPORTE FERROVIARIO PUBLICO DE PASAJEROS',
  '46': 'DOCUMENTO EMITIDO POR LOS CENTROS EDUCATIVOS Y CULTURALES',
  '50': 'DECLARACION UNICA DE ADUANAS - IMPORTACION DEFINITIVA',
  '52': 'DESPACHO SIMPLIFICADO - IMPORTACION SIMPLIFICADA',
  '53': 'DECLARACION DE MENSAJERIA O COURIER',
  '54': 'LIQUIDACION DE COBRANZA',
  '87': 'NOTA DE CREDITO ESPECIAL',
  '88': 'NOTA DE DEBITO ESPECIAL',
  '91': 'COMPROBANTE DE NO DOMICILIADO',
  '96': 'EXCESO DE CREDITO FISCAL POR RETIRO DE BIENES',
  '97': 'NOTA DE CREDITO - NO DOMICILIADO',
  '98': 'NOTA DE DEBITO - NO DOMICILIADO',
} as const

// Currency codes
export const CURRENCIES = {
  PEN: 'Soles',
  USD: 'Dólares Americanos',
  EUR: 'Euros',
} as const

// Unit codes (SUNAT)
export const UNIT_CODES = {
  NIU: 'UNIDAD (BIENES)',
  ZZ: 'UNIDAD (SERVICIOS)',
  KGM: 'KILOGRAMO',
  GRM: 'GRAMO',
  LTR: 'LITRO',
  MTR: 'METRO',
  MTK: 'METRO CUADRADO',
  MTQ: 'METRO CUBICO',
  CEN: 'CIENTO',
  MIL: 'MILLAR',
  TON: 'TONELADA',
  BOX: 'CAJA',
  BAG: 'BOLSA',
  SET: 'JUEGO',
  CAN: 'LATA',
  PCS: 'PIEZAS',
  ROL: 'ROLLO',
  PAR: 'PAR',
  DOZ: 'DOCENA',
  PQT: 'PAQUETE',
  GLL: 'GALON',
  BLK: 'BLOQUE',
  BTL: 'BOTELLA',
} as const

// IGV Rate
export const IGV_RATE = 0.18

// Stock movement types
export const STOCK_MOVEMENT_TYPES = {
  ENTRADA: 'Entrada',
  SALIDA: 'Salida',
  AJUSTE_POSITIVO: 'Ajuste Positivo',
  AJUSTE_NEGATIVO: 'Ajuste Negativo',
  TRANSFERENCIA_ENTRADA: 'Transferencia Entrada',
  TRANSFERENCIA_SALIDA: 'Transferencia Salida',
} as const

// Valuation methods
export const VALUATION_METHODS = {
  PROMEDIO_MOVIL: 'Promedio Móvil',
  FIFO: 'FIFO (Primero en Entrar, Primero en Salir)',
} as const

// User roles
export const USER_ROLES = {
  ADMIN: 'Administrador',
  MANAGER: 'Gerente',
  SALES: 'Vendedor',
  WAREHOUSE: 'Almacenero',
  ACCOUNTANT: 'Contador',
  USER: 'Usuario',
} as const

// Notification types
export const NOTIFICATION_TYPES = {
  INFO: 'info',
  SUCCESS: 'success',
  WARNING: 'warning',
  ERROR: 'error',
} as const

// File upload limits
export const FILE_UPLOAD = {
  MAX_SIZE: 5 * 1024 * 1024, // 5MB
  ALLOWED_TYPES: ['image/jpeg', 'image/png', 'image/webp', 'application/pdf'],
  ALLOWED_EXTENSIONS: ['.jpg', '.jpeg', '.png', '.webp', '.pdf'],
} as const

// Pagination defaults
export const PAGINATION = {
  DEFAULT_PAGE_SIZE: 20,
  PAGE_SIZE_OPTIONS: [10, 20, 50, 100],
} as const

// Date formats
export const DATE_FORMATS = {
  SHORT: 'DD/MM/YYYY',
  LONG: 'DD/MM/YYYY HH:mm',
  ISO: 'YYYY-MM-DD',
  TIME: 'HH:mm',
} as const

// Local storage keys
export const STORAGE_KEYS = {
  THEME: 'theme',
  LOCALE: 'locale',
  SIDEBAR_COLLAPSED: 'sidebar_collapsed',
  CURRENT_COMPANY: 'current_company',
  USER_PREFERENCES: 'user_preferences',
} as const

// API endpoints
export const API_ENDPOINTS = {
  AUTH: '/auth',
  COMPANIES: '/companies',
  PRODUCTS: '/products',
  PARTIES: '/parties',
  SALES: '/sales',
  PURCHASES: '/purchases',
  WAREHOUSES: '/warehouses',
  REPORTS: '/reports',
} as const

export default {
  SUNAT_DOC_TYPES,
  SALES_DOC_TYPES,
  PURCHASE_DOC_TYPES,
  CURRENCIES,
  UNIT_CODES,
  IGV_RATE,
  STOCK_MOVEMENT_TYPES,
  VALUATION_METHODS,
  USER_ROLES,
  NOTIFICATION_TYPES,
  FILE_UPLOAD,
  PAGINATION,
  DATE_FORMATS,
  STORAGE_KEYS,
  API_ENDPOINTS,
}
